### ISSUE TITLE
Allow connection string for mongodb store

### ISSUE THREAD

**Issue by masylum** [masylum/dialect#10]

**Comment by deedubs** [comment]
would also like to see it allow for a direct mongo connection be passed in.

**Comment by dresende** [comment]
This can be easly done with `url.parse()`

**Comment by deedubs** [comment]
While url.parse will allow for a connection string its not convenient. I number of other libraries follow this pattern.  Would make sense to follow it.

I would like to see the ability to pass in a mongodb connection itself.  As to allow sharing of a connection between services.

**Comment by dresende** [comment]
I was not suggesting you to do it, I was suggesting @masylum to do it. I use it on node-orm , both `url.parse()` and direct object passing :)

**Comment by deedubs** [comment]
ah okay :D thought you were -1'ing this ticket :) Carry on.

**Comment by masylum** [comment]
I'm travelling right now. I would appreciate/merge pull requests or wait until 15 nov when I'm back home.

**Comment by hannesgassert** [comment]
@masylum any update on this one?
