### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by txdv** [masylum/dialect#13]
I'm trying to add a mysql store, the problem I am facing:
though the entry doesn't exist, it tries to issue an update command:

``` sql
UPDATE dialect SET translation = 'Hola Mundo!', approved = 0 WHERE original = 'Hello World!' AND locale = 'es'
```

I wonder, why doesn't it insert a new row or something, or why is sqlite doing it that way? Does it work on sqlite?
(I'm using most of the sqlite code base right now)

**Comment by masylum** [comment]
You should do an insert. The sqlite store may be wrong. I should check it out.
