### ISSUE TITLE
Dialect creating lots of files in mongodb/data

### ISSUE THREAD

**Issue by robertjd** [masylum/dialect#14]
We are requiring dialect in our package.json file:

> "dialect" : "1.0.2"

After running npm install there is an excessive amount of data (1.4GB) in this folder:

node_modules/dialect/node_modules/mongodb/data

I am unable to figure out what is causing this and I'm looking for help.

Thanks,
Robert

**Comment by masylum** [comment]
I will update the mongodb driver version. This issue was already solved.

**Comment by masylum** [comment]
try it now

**Comment by robertjd** [comment]
Upgrading to dialect 1.0.3 has solved this problem in the dialect module, but now the space-eater has moved over to dialet-http :(  I now have that 1.4Gb in my dialect-http module instead of the dialect module

Could you elaborate on what the problem is and why upgrading the mongodb driver fixes the problem for dialect?

Thanks!

**Comment by masylum** [comment]
There was a bug on the mongodb driver which has been solved in recent versions. Updating dialect-http in few minutes! :)

**Comment by masylum** [comment]
try it now :)
